name: Django CI

on:
  push:
    branches: [ main, feat/bug-fixes ]
  pull_request:
    branches: [ main, feat/bug-fixes ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: poll_db
          POSTGRES_USER: poll_user
          POSTGRES_PASSWORD: poll_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      DB_NAME: poll_db
      DB_USER: poll_user
      DB_PASSWORD: poll_pass
      DB_HOST: localhost
      DB_PORT: 5432
      SECRET_KEY: testsecretkey
      DEBUG: 'True'
      ALLOWED_HOSTS: localhost,127.0.0.1
      DJANGO_ENV: test
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      run: |
        python manage.py migrate
    - name: Run tests
      run: |
        python manage.py test
